version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "todo"
    commit_message:
      prefix: "chore(tooling)"
      include_scope: false
